version: "3"

services:

  github-wegpage:
    image: dockware/essentials:latest
    container_name: github-webpage
    volumes:
      - "./src:/var/www/html"
      - "db_volume:/var/lib/mysql"
    ports:
      - "22:22"
      - "80:80"
      - "3306:3306"
    environment:
      - PHP_VERSION=7.4
      - XDEBUG_ENABLED=1
    networks:
      - web

volumes:
  db_volume:
    driver: local

networks:
  web:
    external: false